
# script for opening
before_script:
  - echo "Welcome to ci/cd gometri"
  - echo "Will go to build stage"
  - sleep 10

# script for test build binary golang
build-job:
  image: golang:latest
  services:
    - ubuntu:20.04
  stage: build
  script:
    - make build
    - echo "success build"
    - sleep 20


# stage for build docker container
build-docker:
  # pull image
  image: "tmaier/docker-compose:latest"
  
  # services
  services:
    - ubuntu:20.04
    - docker:dind

  stage: build
  
  # testing docker
  before_script:
    - docker info
    - docker-compose --version

  # script for building
  script:
    - echo "running docker-compose"
    - docker-compose build
    - echo "success running docker"
    - echo "go to clear cache"
    - sleep 20
    - docker-compose down 
