# Call image for docker-compose
image: "golang:latest"

# docker in docker because running docker-compose
services:
  - ubuntu:20.04

# before_script:
#  - docker info
#  - docker-compose --version

# script for opening
opening-job:
  script:
    - echo "Welcome to ci/cd gometri"
    - echo "Will go to test stage"
    - sleep 10


# script for test build binary golang
#build-job:
#  stage: build
#  script:
#    - make build
#    - echo "success build"
#    - echo "going to download module"
#    - sleep 20


# stage for build docker container
build-app:
  stage: build
  script:
    - echo "running docker-compose"
    - docker-compose up -d
    - echo "success running docker"
    - docker-compose down  
