# Call image for docker-compose
image: "tmaier/docker-compose:latest"

# docker in docker because running docker-compose
services:
  - ubuntu:20.04
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

# script for opening
opening-job:
  script:
    - echo "Welcome to ci/cd gometri"
    - echo "Will go to test stage"
    - sleep 10


# script for test build binary golang
build-job:
  stage: build
  script:
    - go build -o output server.go
    - echo "success build"
    - sleep 20


# stage for build docker container
build-app:
  stage: build
  script:
    - echo "running docker-compose"
    - docker-compose build
    - echo "success running docker"
    - echo "go to clear cache"
    - sleep 20
    - docker-compose down 
